# wrangler.toml - Конфигурация для Cloudflare Pages
name = "notion-review-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Настройки производительности
[limits] 
cpu_ms = 60000

# Привязка KV Namespace
[[kv_namespaces]]
binding = "KV_BINDING"  						# Имя переменной в коде
preview_id = "21177d901f444877a24c9eef4a404016"  					# Ваш Namespace ID
id = "21177d901f444877a24c9eef4a404016"          	# Ваш Namespace ID

# Переменные окружения (при необходимости)
[vars]
ENVIRONMENT = "production"